index:
    path: /
    controller: App\Controller\Site\SiteController::home

episode:
    path: /episode/{id}
    controller: App\Controller\Site\SiteController::episode

rss:
    path: /subscribe.rss
    controller: App\Controller\Site\SiteController::rss

app_logout:
    path: /logout

app_login:
    controller: App\Controller\SecurityController::login
    path: /login

installation_process_podcast:
    path: /installation/podcast
    methods: ['GET']
    controller: App\Controller\Installation\PodcastController::podcast

installation_process_podcast_submit:
    path: /installation/podcast
    methods: ['POST']
    controller: App\Controller\Installation\PodcastController::podcastSubmit

installation_process_user:
    path: /installation/user
    methods: ['GET']
    controller: App\Controller\Installation\UserController::user

installation_process_user_submit:
    path: /installation/user
    methods: ['POST']
    controller: App\Controller\Installation\UserController::userSubmit

admin_episodes:
    path: /admin/episodes
    methods: ['GET']
    controller: App\Controller\Admin\EpisodeController::index

admin_podcast:
    path: /admin/podcast/{id}
    methods: ['GET']
    controller: App\Controller\Admin\PodcastController::index

admin_podcast.save:
    path: /admin/podcast/{id}
    methods: ['POST']
    controller: App\Controller\Admin\PodcastController::save

admin_podcast.fileupload.save:
    path: /admin/podcast/imageupload/{id}
    methods: ['POST']
    controller: App\Controller\Admin\PodcastController::upload

admin_episode.fileupload.save:
    path: /admin/episode/imageupload/{id}
    methods: ['POST']
    controller: App\Controller\Admin\EpisodeController::upload


admin_settings:
    path: /admin/settings
    methods: ['GET']
    controller: App\Controller\Admin\PodcastController::index

admin_create_episode:
    path: /admin/episodes/create
    methods: ['GET']
    controller: App\Controller\Admin\EpisodeController::create

admin_create_episode.save:
    path: /admin/episodes/create
    methods: ['POST']
    controller: App\Controller\Admin\EpisodeController::createSave


admin_show_episode:
    path: /admin/episodes/{id}
    methods: ['GET']
    controller: App\Controller\Admin\EpisodeController::update

admin_update_episode.save:
  path: /admin/episodes/{id}
  methods: ['POST']
  controller: App\Controller\Admin\EpisodeController::updateSave